import React, { Fragment, useEffect } from "react";
import PropTypes from "prop-types";
import classNames from "classnames";
import {
  Grid,
  Typography,
  Card,
  CardMedia,
  Button,
  Hidden,
  Box,
  withStyles,
  withWidth,
  isWidthUp,
  CardActionArea,
  CardContent,
  DialogActions,
  DialogContent,
  DialogContentText,
} from "@material-ui/core";
import Dialog from '@material-ui/core/Dialog';
import MuiDialogTitle from '@material-ui/core/DialogTitle';
import MuiDialogContent from '@material-ui/core/DialogContent';
import MuiDialogActions from '@material-ui/core/DialogActions';
import IconButton from '@material-ui/core/IconButton';
import CloseIcon from '@material-ui/icons/Close';
const styles = (theme) => ({
  root: {
    margin: 0,
    padding: theme.spacing(2),
  },
  closeButton: {
    position: 'absolute',
    right: theme.spacing(1),
    top: theme.spacing(1),
    color: theme.palette.grey[500],
  },
  bold :{
    fontWeight : "bold"
  }
  
});
const DialogTitle = withStyles(styles)((props) => {
  const { children, classes, onClose, ...other } = props;
  return (
    <MuiDialogTitle disableTypography className={classes.root} {...other}>
      <Typography variant="h6">{children}</Typography>
      {onClose ? (
        <IconButton aria-label="close" className={classes.closeButton} onClick={onClose}>
          <CloseIcon />
        </IconButton>
      ) : null}
    </MuiDialogTitle>
  );
});
function TermsConditions(props) {
  const {
    open,
    onClose
  } = props;
  useEffect(() => {

  }, [open, onClose]);

  const { classes, theme, width } = props;
  return (
    <div id="termsCondition" className={classes.root}>
      <Dialog onClose={onClose} aria-labelledby="customized-dialog-title" open={open}>
        <DialogTitle id="customized-dialog-title" onClose={onClose}>
          Terms & Conditions
        </DialogTitle>
        <DialogContent dividers>
          <Typography gutterBottom variant="h5" component="h2">
            TERMS & CONDITIONS
          </Typography>
          <Typography variant="body2" component="p" gutterBottom>
            Welcome to Villa de Vendôme – Paris ELK. Paris ELK is a unique collection
            of 10 000 digital artworks (NFTs) that are hosted on the Ethereum network.
            This website is the unique interface that allows user to purchase these
            digital artworks.
          </Typography>
          <Typography variant="body2" component="p" gutterBottom>
            Please review carefully these Terms &amp; Conditions, by accessing and using
            this website, you are deemed to have read, accepted and agreed to these
            NFT terms.   </Typography>
          <Box m="2rem">
          </Box> 
          <Typography variant="body2" component="p" gutterBottom>
            <span className = {classes.bold}>A.</span> Disclaimer. This website and its related services are provided as “as is” and “as
            available” without warranty of any kind. By using this
            website(<a href = "www.villadevendome.com">www.villadevendome.com</a>), you are entirely responsible for the safety
            and management of your own private Ethereum wallets and validating all
            transaction and contracts generated by this website before approval. Meanwhile,
            there is no possibility to undo, reverse or restore any transactions as Paris ELK
            smart contract runs on the Ethereum network.</Typography>
          <Typography variant="body2" component="p" gutterBottom>
          <span className = {classes.bold}>B.</span> Ownership. Ownership of the NFT is governed by the Smart Contract and Ethereum,
            thus, we have no ability to freeze, or modify the ownership of any Paris ELK.
          </Typography>
          <Typography variant="body2" component="p" gutterBottom>
           <span className = {classes.bold}>C.</span> License. In order to build a free, equal, sustainable eco-system, Villa Devendome
            grants their owners(NFT holder) personal license (for personal use) and
            Commercial license (for commercial Use). Only the brand “Villa Devendome” &amp;
            “Paris ELK” are restrictive and reserved to Villa Devendome team. When you
            purchase a Paris ELK, you own the Artwork completely, except the brands reserved
            as mentioned previously. Your Personal license and Commercial license will
            terminate upon the transfer of ownership to another owner.</Typography>

        </DialogContent>
      </Dialog>
    </div>
  );
}

TermsConditions.propTypes = {
  classes: PropTypes.object,
  width: PropTypes.string,
  theme: PropTypes.object,
  open: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
};
export default withWidth()(withStyles(styles, { withTheme: true })(TermsConditions));
